twitter:
  api_key: "m8R3Evxy95zGfaXumLTnyiGJk"
  api_secret: "MSFp5cNqZu34jGWVSPY2qBNybTiNOauThMV4E3gbScsBmQdYhn"
  bearer_token: "AAAAAAAAAAAAAAAAAAAAAHWy1wEAAAAAy%2B%2Ffj0G6QLgTBBIgz%2Be1eNpZKWE%3D3oKelZHOYTLe2cMnJIyn0gkUKJHG7DpUT5psL3wVjuyceAg536"